/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnimatedRouteImport } from './routes/animated'
import { Route as IndexRouteImport } from './routes/index'

const AnimatedRoute = AnimatedRouteImport.update({
  id: '/animated',
  path: '/animated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animated': typeof AnimatedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animated': typeof AnimatedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animated': typeof AnimatedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/animated'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/animated'
  id: '__root__' | '/' | '/animated'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimatedRoute: typeof AnimatedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/animated': {
      id: '/animated'
      path: '/animated'
      fullPath: '/animated'
      preLoaderRoute: typeof AnimatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimatedRoute: AnimatedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
